---
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        stages: ["commit"]
        exclude: ".gitlab-ci.yml"
      - id: end-of-file-fixer
        stages: ["commit"]
        exclude: ".*.json"
      - id: trailing-whitespace
        stages: ["commit"]
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
      - id: mypy
        args: ["--follow-imports=silent", "--ignore-missing-imports"]
        additional_dependencies:
          - types-Markdown==3.3.0
          - types-pytz==2021.1.0
          - types-redis==3.5.4
          - types-python-dateutil==0.1.4
          - types-requests==2.25.0
          - types-retry==0.1.3
  - repo: https://github.com/myint/autoflake
    rev: 3c3b2a2274e4
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
      - id: reorder-python-imports
        args:
          [
            "--application-directories",
            "django:django/oncology_portal:django/patient_portal",
          ]
