#!/bin/bash -ex
for reqfile in requirements*txt ; do
    [[ -e /tmp/foo ]] && rm -rf /tmp/foo
    python -m venv /tmp/foo
    /tmp/foo/bin/pip install -U 'pip<21'
    /tmp/foo/bin/pip install -c constraints.txt -r $reqfile
    /tmp/foo/bin/pip freeze | grep -v "pkg-resources" | sort > "../$reqfile"
    rm -rf /tmp/foo
done
